### ISSUE TITLE
Error first running slack-upsource-translator@0.0.1 start script 'node index.js

### ISSUE THREAD

**Issue by mordechaihorowitz** [rajivrnair/upsource-slack-api-adapter#23]
Failed at the slack-upsource-translator@0.0.1 start script 'node index.js

Any ideas what might be causing the problem or suggestions for troubleshooting

**Comment by varunvs** [comment]
@mordechaihorowitz What is the error you get? Can you please share more details?

**Comment by mordechaihorowitz** [comment]
From the logs

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart slack-upsource-translator@0.0.1
6 info start slack-upsource-translator@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info slack-upsource-translator@0.0.1 Failed to exec start script
9 verbose stack Error: slack-upsource-translator@0.0.1 start: `node index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid slack-upsource-translator@0.0.1
11 verbose cwd /var/www/myurl/upsource-slack-api-adapter  // Not including url for security purposes
12 error Linux 4.18.16-x86_64-linode118
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.2
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error slack-upsource-translator@0.0.1 start: `node index.js`
17 error Exit status 1
18 error Failed at the slack-upsource-translator@0.0.1 start script 'node index.js'.
18 error This is most likely a problem with the slack-upsource-translator package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js

**Comment by varunvs** [comment]
Your NodeJS version is 0.12 which is too old. Can you please use a newer version of NodeJS and try?
